name: Convert Forked Pull Request to Local Pull Request

on:
  workflow_dispatch:
  # pull_request_target:
  #   types:
  #     - opened
  #     - synchronize

jobs:
  convert_fork_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Base Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and commit history

      - name: Add Remote Fork
        run: |
          echo "Adding fork as remote..."
          git remote add fork ${{ github.event.pull_request.head.repo.clone_url }}
          git fetch fork

      - name: Create Local Branch for PR
        run: |
          echo "Creating local branch from forked PR..."
          LOCAL_BRANCH="fork-pr-${{ github.event.pull_request.number }}"
          git checkout -b $LOCAL_BRANCH fork/${{ github.event.pull_request.head.ref }}

      - name: Push Local Branch
        run: |
          echo "Pushing local branch to base repository..."
          git push --set-upstream origin $LOCAL_BRANCH

      - name: Comment on PR with Local Branch
        run: |
          LOCAL_BRANCH="fork-pr-${{ github.event.pull_request.number }}"
          PR_COMMENT="The forked pull request has been mirrored to the local branch: \`${{ github.repository }}:$LOCAL_BRANCH\`."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$PR_COMMENT\"}" \
            "${{ github.event.pull_request.comments_url }}"
