name: Create Branch from Pull Request

on:
  pull_request:
    types:
      - opened # Trigger when a pull request is opened

jobs:
  create_branch_from_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create New Branch from PR
        env:
          BRANCH_NAME: "branch-from-pr-${{ github.event.pull_request.number }}"
          BASE_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch
          # git checkout $BASE_BRANCH
          git checkout main
          git checkout -b $BRANCH_NAME
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $BRANCH_NAME
          # git push origin $BRANCH_NAME

      - name: Comment on Pull Request
        env:
          BRANCH_NAME: "branch-from-pr-${{ github.event.pull_request.number }}"
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"New branch created: $BRANCH_NAME\"}" \
            "${{ github.event.pull_request.comments_url }}"
