name: Create Branch from Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test_github_token:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Fetch Pull Request Head SHA and Branch Name
        run: |
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          PR_SHA="${{ github.event.pull_request.head.sha }}"
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
          echo "PR_SHA=$PR_SHA" >> $GITHUB_ENV

      - name: Create New Branch for PR
        run: |
          TEST_BRANCH="test-branch-for-pr-${{ github.event.pull_request.number }}"
          RESPONSE=$(curl -X POST \
                           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                           -H "Accept: application/vnd.github.v3+json" \
                           -d "{\"ref\":\"refs/heads/$TEST_BRANCH\",\"sha\":\"${PR_SHA}\"}" \
                           -o response.json -w "%{http_code}" \
                           -s https://api.github.com/repos/${{ github.repository }}/git/refs)
          if [ "$RESPONSE" -eq 201 ]; then
            echo "Branch $TEST_BRANCH created successfully."
            echo "TEST_BRANCH=$TEST_BRANCH" >> $GITHUB_ENV
          else
            echo "Failed to create branch: Received HTTP $RESPONSE"
            cat response.json
            exit 1
          fi
