name: Create Branch from PR

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #
jobs:
  sync_pr_with_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure all branches and commit history are fetched

      - name: Pull Latest Main Branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Create Branch with PR Sources
        run: |
          PR_BRANCH="pr-${{ github.event.pull_request.number }}-with-main"
          git checkout -b $PR_BRANCH
          git pull origin ${{ github.event.pull_request.head.ref }}
          git log --oneline -5

      - name: Push the New Branch
        run: |
          PR_BRANCH="pr-${{ github.event.pull_request.number }}-with-main"
          git push --set-upstream origin $PR_BRANCH

      - name: Display Branch Details
        run: |
          echo "Created branch: pr-${{ github.event.pull_request.number }}-with-main"
          git branch
          echo "Merged commits from PR: ${{ github.event.pull_request.head.ref }}"
