name: Create New Branch and Reset Main on Forked PR Merge

on:
  pull_request:
    types:
      - closed # Trigger when a PR is closed (including merged)
    branches:
      - main # Only monitor merges into main

jobs:
  create_and_reset:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to enable reset
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set remote URL with GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/jasp-escience/modules.git"
          git remote -v

      - name: Read branch name from meta.yaml and add prefix
        id: read_meta
        run: |
          RAW_BRANCH_NAME=$(yq '.package.name' meta.yaml)
          BRANCH_NAME="module/$(echo $RAW_BRANCH_NAME | sed 's/^"//;s/"$//')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Get the latest commit hash (Merge Commit)
        id: get_merge_commit
        run: echo "MERGE_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create a new branch with the merge commit
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          MERGE_COMMIT_SHA: ${{ env.MERGE_COMMIT_SHA }}
        run: |
          git remote -v
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git branch "$BRANCH_NAME" "$MERGE_COMMIT_SHA"
          git push origin "$BRANCH_NAME"

      - name: Reset main branch to previous commit
        run: |
          git reset --hard HEAD~1
          git push origin main --force
