name: Fork Repository into jasp-escience

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository to fork (e.g., owner/repo)"
        required: true

jobs:
  fork-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Fork repository into jasp-escience
        env:
          ORG_PAT: ${{ secrets.ORG_PAT }}
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST \
               -H "Authorization: token $ORG_PAT" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.event.inputs.repo }}/forks" \
               -d '{"organization": "jasp-escience", "default_branch_only":true}')

          if [ "$RESPONSE" -ne 202 ]; then
            echo "❌ Failed to fork repository. HTTP Status: $RESPONSE"
            cat response.json
            exit 1
          else
            echo "✅ Repository successfully forked into jasp-escience."
          fi
