name: Process new meta files and fork modules

on:
  workflow_dispatch:

jobs:
  sync-modules:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.ORG_PAT }}
      ORG: jasp-escience
      BRANCH: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ORG_PAT }}

      - name: Configure Git for authenticated push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Fork and add submodules
        run: |
          mkdir -p beta-modules

          for file in modules-metadata/*.yaml; do
            if [ "$file" = "modules-metadata/exampleJaspModule.yaml" ]; then
              echo "Skipping example module: $name"
              continue
            fi
            echo "Processing $file"
            name=$(yq -r '.name' "$file")
            url=$(yq -r '.gitUrl' "$file")
            echo "name=$name"
            echo "gitUrl=$url"

            # Check if repo exists in jasp-escience org
            echo "Checking if https://github.com/${ORG}/${name}.git exists..."
            status=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: token $GH_TOKEN" \
              https://api.github.com/repos/${ORG}/${name})

            if [ "$status" == "200" ]; then
              echo "Repo ${ORG}/${name} already exists. Skipping fork."
              continue
            fi
            echo "Forking into ${ORG}/${name}..."
              # Extract original owner/repo
            #   repo_path=$(echo "$url" | sed -E 's|https://github.com/([^/]+/[^.]+)(\.git)?|\1|')
            #   owner=$(echo "$repo_path" | cut -d'/' -f1)
            #   repo=$(echo "$repo_path" | cut -d'/' -f2)
            #
            #   curl -s -X POST \
            #     -H "Authorization: token $GH_TOKEN" \
            #     -H "Accept: application/vnd.github+json" \
            #     https://api.github.com/repos/$owner/$repo/forks \
            #     -d "{\"organization\": \"${ORG}\"}"
            #
            #   echo "Waiting for fork to be ready..."
            #   for i in {1..10}; do
            #     status=$(curl -s -o /dev/null -w "%{http_code}" \
            #       -H "Authorization: token $GH_TOKEN" \
            #       https://api.github.com/repos/${ORG}/${repo})
            #     [ "$status" == "200" ] && break
            #     sleep 3
            #   done
            # fi
            #
            # # Add as submodule
            # echo "Adding submodule: beta-modules/$name"
            # git submodule add https://github.com/${ORG}/${name}.git beta-modules/$name || echo "Submodule already exists or failed"
            # # git submodule add https://${GH_TOKEN}@github.com/${ORG}/${name}.git beta-modules/$name
            # # git remote -v
            # git add beta-modules/${name}
            # git commit -m "Added ${name} as a submodule under beta-modules/"
            # git push origin main


          done
