name: Test GITHUB_TOKEN with Curl

on:
  workflow_dispatch: # Manual trigger for testing

jobs:
  test_github_token:
    runs-on: ubuntu-latest

    steps:
      - name: Test GITHUB_TOKEN with Curl
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -o response.json -w "%{http_code}" \
               -s https://api.github.com/repos/${{ github.repository }} > status_code.txt

          STATUS=$(cat status_code.txt)
          if [ "$STATUS" -eq 200 ]; then
            echo "GITHUB_TOKEN is working: Received HTTP 200"
          else
            echo "GITHUB_TOKEN test failed: Received HTTP $STATUS"
            exit 1
          fi
