iname: Test GITHUB_TOKEN for Read and Write Permissions

on:
  workflow_dispatch: # Manual trigger for testing

jobs:
  test_github_token:
    runs-on: ubuntu-latest

    steps:
      - name: Create Test Branch
        run: |
          TEST_BRANCH="test-github-token"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"ref\":\"refs/heads/$TEST_BRANCH\",\"sha\":\"$(git rev-parse HEAD)\"}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs

      - name: Test GITHUB_TOKEN for Read Permission
        run: |
          RESPONSE=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          -o response.json -w "%{http_code}" \
                          -s https://api.github.com/repos/${{ github.repository }})
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Read permissions are working: Received HTTP 200"
          else
            echo "Read permissions test failed: Received HTTP $RESPONSE"
            cat response.json
            exit 1
          fi

      - name: Test GITHUB_TOKEN for Write Permission
        run: |
          TEST_BRANCH="test-github-token"
          DATE=$(date +%Y-%m-%d:%H:%M:%S)
          RESPONSE=$(curl -X PUT \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          -H "Content-Type: application/json" \
                          -d "{\"message\":\"Test GITHUB_TOKEN write\",\"content\":\"$(echo 'This is a test file.' | base64)\",\"branch\":\"$TEST_BRANCH\"}" \
                          -o response.json -w "%{http_code}" \
                          -s https://api.github.com/repos/${{ github.repository }}/contents/test_github_token_${DATE}.txt)
          if [ "$RESPONSE" -eq 201 ]; then
            echo "Write permissions are working: File created successfully in branch $TEST_BRANCH"
          else
            echo "Write permissions test failed: Received HTTP $RESPONSE"
            cat response.json
            exit 1
          fi
